<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Application\PortfolioApi.Application.csproj" />
    <ProjectReference Include="..\Domain\PortfolioApi.Domain.csproj" />
    <ProjectReference Include="..\Portfolio.Application\PortfolioApi.Application.csproj" />
    <ProjectReference Include="..\Portfolio.Domain\PortfolioApi.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
